### PR TITLE
Merge upstream branch kirkstone

### PR DESCRIPTION
**Pull request by TheYoctoJester**
As the OE4T state with Jetpack4/Jetpack5-split have diverged from the upstream state at https://github.com/mendersoftware/meta-mender-community, do a merge this way first to prepare for contributing back.

### CODE REVIEW

**Comment by dwalkes** [comment]
Thanks @TheYoctoJester  - so is the idea that I should just hard reset the OE4T:kirkstone branch to this branch and then we'll rebase https://github.com/OE4T/meta-mender-community/pull/19 on top of this one?

**Comment by TheYoctoJester** [comment]
Hi @dwalkes, if a hard branch reset is an acceptable option, then I actually have a different proposal. Didn't consider it first hand because I assumed breaking existing checkouts is out of bounds.

In such a case, I would prefer to take the current state of meta-mender-tegra-jetpack4 and meta-mender-tegra-jetpack5, and rebase it on top of the current state of meta-mender-tegra. This can either be your reset-to target and then sent upstream, or I put it into upstream and you reset to that. Then we can rebase the Orin PR on top of it, and can create a clear line of development.

Such a strategy could definitely clean up the history and avoid ugly merges, but at the cost of said hard reset and broken checkout on the branch name.

Thoughts? Should I prepare such a branch?

**Comment by dwalkes** [comment]
> Didn't consider it first hand because I assumed breaking existing checkouts is out of bounds.

The only purpose of the oe4t:kirkstone branch is to stage changes upstream which aren't ready to go upstream so I think it's fine to rebase.

> I would prefer to take the current state of meta-mender-tegra-jetpack4 and meta-mender-tegra-jetpack5, and rebase it on top of the current state of meta-mender-tegra. This can either be your reset-to target and then sent upstream, or I put it into upstream and you reset to that

I'd prefer reset of OE4T to target since my thought is there's no need to upstream until we have Jetpack 5 changes at https://github.com/OE4T/meta-mender-community/pull/19 ready to merge.

> but at the cost of said hard reset and broken checkout on the branch name

I don't think we need to worry about others basing on oe4t:kirkstone in it's previous state - I think we've consistently said this is just for staging changes upstream.

So having said that would you like me to hard-reset OE4T:kirkstone to https://github.com/mendersoftware/meta-mender-community/tree/kirkstone now?

**Comment by TheYoctoJester** [comment]
Hi @dwalkes,

nice, that's the perfect way forward. I have already bumped https://github.com/mendersoftware/meta-mender-community/tree/kirkstone with the current state of OE4T, so yeah, please hard-reset to that one.

**Comment by dwalkes** [comment]
@TheYoctoJester done, thanks!

**Pull request closed without merging**
